name: ${{values.app_name}}-cicd

on:
  push:
    paths:
      - 'src/**'
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Shorten Commit ID
        shell: bash
        run: |
          set -euo pipefail
          # 7 karakterlik kısa SHA üret
          SHORT_SHA="$(echo "${GITHUB_SHA}" | cut -c1-7)"
          # Boşsa hata ver (tag boş kalmasın)
          if [ -z "$SHORT_SHA" ]; then
            echo "SHORT_SHA boş! GITHUB_SHA: ${GITHUB_SHA}"
            exit 1
          fi
          echo "COMMIT_ID=$SHORT_SHA" >> "$GITHUB_ENV"
          echo "Kullanılacak tag: $SHORT_SHA"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ '${{ secrets.DOCKERHUB_USERNAME }}' }}
          password: ${{ '${{ secrets.DOCKERHUB_TOKEN }}' }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: gokhangurbuz/${{values.app_name}}:${{ '${{ env.COMMIT_ID }}' }}
    outputs:
      commit_id: ${{ '${{ env.COMMIT_ID }}' }}
  
  cd:
    needs: ci
    runs-on: self-hosted
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Modify values file
        shell: bash
        run: |
          echo ${{ '${{ needs.ci.outputs.commit_id }}' }}
          pip install yq
          yq -Yi '.image.tag = "${{ '${{ needs.ci.outputs.commit_id }}' }}"' charts/${{values.app_name}}/values-${{values.app_env}}.yaml

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update image tag to ${{ '${{ needs.ci.outputs.commit_id }}' }}"

      - name: Install ArgoCD CLI
        shell: bash
        run: |
          curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-arm64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/argocd
          argocd version --client

      - name: Ensure argocd repo and app
        shell: bash
        run: |
          #Connect to ArgoCd repo
          repo="https://github.com/gokhan-gurbuz/${{values.app_name}}.git"
          argocd repo list | grep -q $repo || argocd repo add $repo

          #Ensure  argocd app
          argocd app get ${{values.app_name}} || argocd app create ${{values.app_name}} \
            --repo $repo \
            --path charts/${{values.app_name}} \
            --dest-namespace ${{values.app_env}}  \
            --dest-server https://kubernetes.default.svc \
            --values values-${{values.app_env}}.yaml \
            --revision main \
            --sync-policy auto \
            --sync-option CreateNamespace=true \

      - name: ArgoCd app sync
        shell: bash
        run: |
          argocd login argocd-server.argocd \
          --insecure \
          --grpc-web \
          --username admin \
          --password ${{ '${{ secrets.ARGOCD_PASSWORD }}' }} && \
          argocd app sync ${{values.app_name}}
          argocd app wait ${{values.app_name}} --timeout 180